### ISSUE TITLE
500 Error when sign in from Github

### ISSUE THREAD

**Issue by 4itosik** [wunsh/docdog-engine#25]
When sign in first time everything worked fine, but with  login from other browser I get
`Internal server error`

**Comment by nesaulov** [comment]
I think I can fix this.

**Comment by jarosluv** [comment]
@nesaulov 

It will be great! 

I can't reproduce this error. What do you think is wrong here?

**Comment by nesaulov** [comment]
@jarosluv The problem is here: `lib/docdog/accounts/accounts.ex:106`
```elixir
query = from(u in User, where: u.username == ^auth.info.nickname)
```
`auth.info.nickname` does not correlate with what is saved when `DocDog.Accounts.User.name_from_auth()` is invoked: sometimes full name is saved, sometimes only first name, other times nickname. This caused the bug, and the right way (I think) would be to compare emails here. Also, in order to reproduce this problem locally, I had to log out several times, which inevitably led to the solution of #13  :)

**Comment by jarosluv** [comment]
@nesaulov 

~I still could not reproduce the problem.~ 

Bingo! I understood what was happened here. This error was raised only by users who had a filled name in Github profile, when auth first time.

I need some time to make sure that the email is always returned from Github API.

**Comment by nesaulov** [comment]
@jarosluv you see, even in if email won't be returned from GitHub API, we will still [fail on validation](https://github.com/wunsh/docdog-engine/blob/master/lib/docdog/accounts/user.ex#L27), so I guess we should either remove this constraint, or leave everything as is in PR.

**Comment by jarosluv** [comment]
@nesaulov 

I did a little research and I think, using of nicknames or emails (or anything data that can change) is totally bad practice. We need to use `uid` from Github auth info. For this we can add new model related to user with all authorizations – each line for each user authorization in another one provider. But since we have only Github for now and haven't plan to add another providers, we can simply add field `github_uid` to User and match this field when sign up and sign in. This field must have unique index too. 

By the way, in some docs written that Github not obliged to send any private emails. But my account returns my primary email by OAuth. Therefore I think we can leave email unique constraint as is.

Please, how it will be possible, make this changes and rebase your branch from master. And thank you so much for your efforts!

**Comment by jarosluv** [comment]
@nesaulov ping

**Comment by nesaulov** [comment]
@jarosluv yeah, i've seen it, probably will update PR this weekend, quite busy right now.

**Comment by jarosluv** [comment]
@nesaulov 

If you want, I can finish this in your brunch, or can wait you?

**Comment by nesaulov** [comment]
@jarosluv if this is urgent (cant wait 3-4 days), then you should finish it yourself, but personally I don't see any rush in this repo.

**Comment by jarosluv** [comment]
Thank you all!
